Repository mattermost/mattermost-plugin-starter-template, pull requests merged in 2019-06, with the labels that each got.

#41 Advertising template
  README.md
Labels: 1: PM Review

#44 Clarify Go modules requirements.
  README.md
Labels: 3: Reviews Complete

#43 Refactoring
  Makefile
  build/manifest/.gitignore
  build/manifest/main.go
  build/setup.mk
  go.mod
  go.sum
  plugin.json
  server/.gitignore
  server/manifest.go
  server/plugin.go
  server/plugin_test.go
  webapp/i18n/en.json
Labels: 3: Reviews Complete

#45 Add support for custom makefile
  Makefile
  build/custom.mk
Labels: 2: Dev Review

#47 [MM-14189] Update references to "mattermost-plugin-sample" to be "mattermost-plugin-starter-template"
  README.md
  go.mod
  plugin.json
  public/hello.html
  server/manifest.go
  webapp/src/manifest.js
Labels: 3: Reviews Complete

#46 Make go flags customisable
  Makefile
Labels: 3: Reviews Complete
