Repository mattermost/mattermost-plugin-starter-template, pull requests merged in 2019-04, with the labels that each got.

#33 MM-14575: Automatically serve static files for plugins
  Makefile
  build/setup.mk
  public/hello.html
Labels: 2: Dev Review, Awaiting PR

#35 Start with version 0.1.0 instead of 0.0.1
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 2: Dev Review

#36 changed single expression plugin upload to validate responses
  Makefile
Labels: 3: Ready to Merge
