Repository mattermost/mattermost-plugin-starter-template, pull requests merged in 2019-12, with the labels that each got.

#75 npm audit fix --save
  webapp/package-lock.json
Labels: Tests/Not Needed

#73 build/manifest: print whole manifest variable as it is
  build/manifest/main.go
  go.sum
  server/manifest.go
  webapp/src/index.js
  webapp/src/manifest.js
  webapp/src/manifest.test.js
Labels: 3: Reviews Complete

#76 Bump Mattermost to 5.18
  build/deploy/main.go
  build/manifest/main.go
  go.mod
  go.sum
  server/main.go
  server/plugin.go
Labels: 3: Reviews Complete, Tests/Not Needed

#77 Fix invalid import in manifest.go
  build/manifest/main.go
  server/manifest.go
Labels: 3: Reviews Complete, Tests/Not Needed
